### ISSUE TITLE
404 ?

### ISSUE THREAD

**Issue by badboycxcc** [chroblert/AssetManage#16]
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django  will display a standard 404 page

/baseline/windows_scan_res_report/ 
![image](https://user-images.githubusercontent.com/72059221/106089850-ca61dd80-6163-11eb-9cc3-d5bc444377bb.png)

**Comment by chroblert** [comment]
8888后面多了个/

**Comment by badboycxcc** [comment]
![image](https://user-images.githubusercontent.com/72059221/106097364-20d61880-6172-11eb-9d61-b3faa4a93a01.png)
linux 下报错，jq？

**Comment by chroblert** [comment]
jq是一个美化输出json字符串的命令，没安装可以删掉。另外，Linux脚本应该只适用RedHat系服务器。

**Comment by badboycxcc** [comment]
原来是debian系不支持呀，感谢大佬的帮助，大佬加油！
